### ISSUE TITLE
It seems not working for win10 system

### ISSUE THREAD

**Issue by qqian1991** [nikogu/roadhog-api-doc#5]
Did as your steps:
1. npm install roadhog-api-doc -g successfully
2. but when I run "roadhog-api-doc start 8000" command, it ends with error

* add the full log content:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle roadhog-api-doc-boilerplate@~prestart: roadhog-api-doc-boilerplate@
6 info lifecycle roadhog-api-doc-boilerplate@~start: roadhog-api-doc-boilerplate@
7 verbose lifecycle roadhog-api-doc-boilerplate@~start: unsafe-perm in lifecycle true
8 verbose lifecycle roadhog-api-doc-boilerplate@~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\QIQIAN\Desktop\ant-design-pro\_roadhog-api-doc\node_modules\.bin;C:\Python27;C:\Python27\Scripts;C:\Python36\;C:\Python36\Scripts\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\VanDyke Software\SecureFX\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\apache-maven-3.5.0\bin;C:\Program Files\Java\jdk1.8.0_121\bin;C:\Program Files\Git\cmd;C:\groovy-2.4.10\bin;C:\gradle-3.5\bin;C:\Program Files (x86)\Pandoc\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\Software\apache-jmeter-3.2\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\mysql-5.7.19\bin;C:\Program Files\nodejs\;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.3.0\bin;C:\Users\QIQIAN\AppData\Local\Microsoft\WindowsApps;C:\Users\QIQIAN\Documents\WindowsPowerShell\Scripts;C:\Users\QIQIAN\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Docker Toolbox;C:\Program Files\Microsoft VS Code\bin;C:\Users\QIQIAN\AppData\Roaming\npm
9 verbose lifecycle roadhog-api-doc-boilerplate@~start: CWD: C:\Users\QIQIAN\Desktop\ant-design-pro\_roadhog-api-doc
10 silly lifecycle roadhog-api-doc-boilerplate@~start: Args: [ '/d /s /c', 'PORT=8000 ../node_modules/.bin/roadhog server' ]
11 silly lifecycle roadhog-api-doc-boilerplate@~start: Returned: code: 1  signal: null
12 info lifecycle roadhog-api-doc-boilerplate@~start: Failed to exec start script
13 verbose stack Error: roadhog-api-doc-boilerplate@ start: `PORT=8000 ../node_modules/.bin/roadhog server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid roadhog-api-doc-boilerplate@
15 verbose cwd C:\Users\QIQIAN\Desktop\ant-design-pro\_roadhog-api-doc
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.8.1
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 1
22 error roadhog-api-doc-boilerplate@ start: `PORT=8000 ../node_modules/.bin/roadhog server`
22 error Exit status 1
23 error Failed at the roadhog-api-doc-boilerplate@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by trexguo** [comment]
根据[roadhog 环境变量](https://github.com/sorrycc/roadhog#环境变量)

```
# OS X, Linux
$ PORT=3000 roadhog server

# Windows (cmd.exe)
$ set PORT=3000&&roadhog server

# Or use cross-env for all platforms
$ cross-env PORT=3000 roadhog server
```

start是不是应该改一下

**Comment by nikogu** [comment]
@qqian1991 try: 0.2.7

**Comment by trexguo** [comment]
@nikogu 
 set PORT=8000&&\../node_modules/.bin/roadhog server

少了&&\

**Comment by trexguo** [comment]
直接在命令行执行set PORT=8000&&../node_modules/.bin/roadhog server 是可以的，但是写在string里还要转义反斜杠，挺麻烦。不如在依赖中用cross-env替换is-windows，也就是用上面提到的roadhog的方案

**Comment by nikogu** [comment]
@trexguo 用 `cross-env` 需要用户安装这个依赖，有点麻烦了，最好工具直接搞定，因为 roadhog 都是装在全局的

**Comment by trexguo** [comment]
不用cross-env但是你不也新加了is-windows了么。。。。
针对不同项目本地安装roadhog更科学一些，不然roadhog全局安装后如果后续API变更，老项目可能会break。 而且你的代码里也是用本地安装的roadhog:
```
   "scripts": {
      "start": "${isWindows() ? `set PORT=${port}` : `PORT=${port}`} ../node_modules/.bin/roadhog server",
      "build": "../node_modules/.bin/roadhog build" 
    }
```
这样做也是有风险的。

另外build.js里有一句: 
` shelljs.exec('ln -s ../node_modules node_modules');`
这一句的目的是什么？ 为什么要把项目的依赖都link到_roadhog-api-doc目录下？
其他代码还没仔细看，不太理解。但是build运行起来很慢，而且一直没成功过。。。。（windows环境）

**Comment by nikogu** [comment]
@trexguo 应该是不用 build 的呀，是这样，roadhog-api-dos 会生成一个站点，这个站点没有任何依赖（依赖都是用的用户的 roadhog 项目），所以这也是不想加  `cross-env` 的问题，`is-windows` 是不一样的，它是工具内部依赖，而  `cross-env` 是站点模板的依赖，需要用户额外安装的。
